name: "Send Email Workflow" 
on:
  issues:
    types: [labeled]
    
jobs:
  InvitationMail:
    if: ${{ github.event.label.name == 'Invitation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/invitation.yaml
         
      - name: Email Parsing
        id: mail
        run: |
          JSON=`echo '${{ steps.issue-parser.outputs.jsonString }}'`
          mail=`echo $(jq -r '.smail_id' <<< "$JSON")`
          echo $mail
          echo "::set-output name=mail::$(echo $mail)"
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{SECRETS.EMAIL}}
          password: ${{SECRETS.PASSWORD}}
          subject: Hello from CFI!
          to: ${{steps.mail.outputs.mail}}
          from: CFI x Github Campus
          body: Thanks for Creating an issue in our repository.
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low
          
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.id }}
          comment: Auto-closing issue
        
          
          
